@startuml MongoDB Cluster with PyMongo API
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title MongoDB Cluster с подключением PyMongo API v2

Container(pymongo_api, "PyMongo API", "Python", "Внешнее приложение")
Container(query_router, "Query Router", "mongos", "Маршрутизатор запросов")

Container(config1, "Config Server 1", "MongoDB", "Реплика-сет")
Container(config2, "Config Server 2", "MongoDB", "Реплика-сет")
Container(config3, "Config Server 3", "MongoDB", "Реплика-сет")

Container(shard1_primary, "Shard 1 Primary", "MongoDB", "Primary нода")
Container(shard1_secondary1, "Shard 1 Secondary", "MongoDB", "Replica 1")
Container(shard1_secondary2, "Shard 1 Secondary", "MongoDB", "Replica 2")

Container(shard2_primary, "Shard 2 Primary", "MongoDB", "Primary нода")
Container(shard2_secondary1, "Shard 2 Secondary", "MongoDB", "Replica 1")
Container(shard2_secondary2, "Shard 2 Secondary", "MongoDB", "Replica 2")

Rel(pymongo_api, query_router, "Запросы (27017)", "MongoDB Protocol")

Rel(config1, config2, "Синхронизация", "MongoDB")
Rel(config2, config3, "Синхронизация", "MongoDB")
Rel(config3, config1, "Синхронизация", "MongoDB")
Rel(query_router, config1, "Метаданные", "MongoDB")

Rel(query_router, shard1_primary, "Read/Write", "MongoDB")
Rel(shard1_primary, shard1_secondary1, "Репликация", "Oplog")
Rel(shard1_primary, shard1_secondary2, "Репликация", "Oplog")

Rel(query_router, shard2_primary, "Read/Write", "MongoDB")
Rel(shard2_primary, shard2_secondary1, "Репликация", "Oplog")
Rel(shard2_primary, shard2_secondary2, "Репликация", "Oplog")

@enduml